---
title: "Untitled"
output: html_document
date: "2025-06-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## load required libraries

```{r}
source(here::here("_setup.R"))
```


## initial plots

## summary stats
###mean RI by year

```{r}
load(here("data/outputs/grids_usdm_stats.rda"))

grids <- grids %>% filter(!is.na(cpc_index_2010_625)) %>% filter(!(is.na(DM_max_2010_625)))


```


```{r}
load(file = here("data/outputs/tpu_collapsed.rda"))
load(file = paste0(here("data/outputs/grids_intersecting.rda")))

usdm <- st_read(here("data/USDM_GIS/2011_USDM_M/USDM_20110607.shp"))
# usdm <- st_read(here("/Users/mjcecil/Documents/GitHub/usdm-prf/data/USDM_GIS/2000_USDM_M/USDM_20000530.shp"))

```

## make tpu_collapsed spatial

```{r}
options(tigris_use_cache = TRUE)

counties_sf <- counties(cb = TRUE, year = 2022) %>%
  st_as_sf()

tpu_collapsed <- tpu_collapsed %>%
  mutate(
    State.Code_str  = sprintf("%02s", State.Code),
    County.Code_str = sprintf("%03s", County.Code),
    GEOID = paste0(State.Code_str, County.Code_str)
  )

tpu_sf <- tpu_collapsed %>%
  left_join(
    counties_sf %>% select(GEOID, geometry),
    by = "GEOID"
  ) %>%
  st_as_sf()

plot(tpu_sf["Net.Reporting.Level.Amount"])

save(tpu_sf, file=here("data/outputs/tpu_sf.rda"))


```


```{r}

plot(usdm["DM"])


```

```{r}

options(tigris_use_cache = TRUE)

## Pecos county TX
# state_abbreviation = "TX"
# state_code = "48"
# county_code = "371"
# county_text = "Pecos County, Texas"

## Butler county KS
state_abbreviation = "KS"
state_code = "20"
county_code = "15"
county_text = "Butler County, Kansas"

## Finney county KS
# state_abbreviation = "KS"
# state_code = "20"
# county_code = "55"
# county_text = "Finney County, Kansas"

#---------------------------
# 1) State boundary
#---------------------------
state_sf <- states(cb = TRUE, year = 2022) %>%
  filter(STUSPS == state_abbreviation) %>%
  st_as_sf()

#---------------------------
# 3) County boundary
#   FIPS: 48-371
#---------------------------
county_boundary <- tpu_sf %>%
  filter(State.Code == state_code,
         County.Code == county_code) %>%
  st_union() %>%
  st_as_sf()


#---------------------------
# 5) Match CRS
#---------------------------
state_sf           <- st_transform(state_sf, st_crs(usdm))
county_boundary  <- st_transform(county_boundary, st_crs(usdm))
grids_intersecting_rates <- st_transform(grids_intersecting, st_crs(usdm))


#---------------------------
# 2) Clip USDM to Texas
#---------------------------
usdm_state <- st_intersection(usdm, state_sf)


#---------------------------
# 4) CPC grids intersecting Pecos
#---------------------------
grids_county <- grids_intersecting_rates[
  st_intersects(grids_intersecting_rates,
                county_boundary,
                sparse = FALSE),
]

grids_county     <- st_transform(grids_county, st_crs(usdm))

#---------------------------
# 6) USDM color palette
#---------------------------

usdm_state <- usdm_state %>%
  mutate(
    DM = factor(DM,
                levels = c(0, 1, 2, 3, 4),
                labels = c("D0", "D1", "D2", "D3", "D4"))
  )

#---------------------------
# USDM color palette
#---------------------------
usdm_cols <- c(
  "D0" = "#FFFF00",
  "D1" = "#FCD37F",
  "D2" = "#FFAA00",
  "D3" = "#E60000",
  "D4" = "#730000"
)

#---------------------------
# 7) Plot
#---------------------------
p_map_3_datasets <- ggplot() +
  geom_sf(data = usdm_state,
          aes(fill = DM),
          color = NA) +
  # Replace original grids_county and county_boundary layers with these
  # which feed into scale_color_manual for the legend
  geom_sf(data = grids_county,
          aes(color = "CPC Grids"),
          fill = NA,
          linewidth = 0.4) +
  geom_sf(data = county_boundary,
          aes(color = "Butler County"),
          fill = NA,
          linewidth = 1.2) +
  geom_sf(data = state_sf,
          fill = NA,
          color = "black",
          linewidth = 0.8) +
  scale_fill_manual(values = usdm_cols, na.value = "white") +
  scale_color_manual(
    name = NULL,
    values = c("CPC Grids" = "blue",
               "Butler County" = "black")
  ) +
  guides(
    fill  = guide_legend(order = 1),
    color = guide_legend(order = 2, override.aes = list(linewidth = c(0.4, 1.2)))
  ) +
  coord_sf() +
  theme_minimal() +
  labs(
    title = paste0("Data Footprint - ", county_text),
    fill = "USDM (June 7 2011)"
  ) +
  theme(
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks = element_blank(),
    plot.title    = element_text(size = 20),
    plot.subtitle = element_text(size = 18),
    legend.title  = element_text(size = 20),
    legend.text   = element_text(size = 20),
    legend.key.size = unit(1.2, "lines")
  )

p_map_3_datasets

png(here("data/outputs/figures/p_map_3_datasets.png"),
    width = 800,
    height = 400)
plot(p_map_3_datasets)
dev.off()


```

